package fr.mrlebest.craftingmod.item;

import cpw.mods.fml.common.registry.GameRegistry;
import fr.mrlebest.craftingmod.common.CraftingMod;
import fr.mrlebest.craftingmod.item.drink.ItemFoodBiere;
import fr.mrlebest.craftingmod.item.drink.ItemFoodCoca;
import fr.mrlebest.craftingmod.item.drink.ItemFoodSprite;
import fr.mrlebest.craftingmod.item.drink.ItemFoodVin;
import fr.mrlebest.craftingmod.item.drink.ItemMTN;
import fr.mrlebest.craftingmod.item.drink.ItemRedBull;
import fr.mrlebest.craftingmod.item.drink.ItemWater;
import fr.mrlebest.craftingmod.item.food.ItemBaieOrange;
import fr.mrlebest.craftingmod.item.food.ItemBaieRouge;
import fr.mrlebest.craftingmod.item.food.ItemFoodBaguette;
import fr.mrlebest.craftingmod.item.food.ItemFoodBigKing;
import fr.mrlebest.craftingmod.item.food.ItemFoodFrites;
import fr.mrlebest.craftingmod.item.food.ItemFoodGateau;
import fr.mrlebest.craftingmod.item.food.ItemFoodGauffre;
import fr.mrlebest.craftingmod.item.food.ItemFoodKebab;
import fr.mrlebest.craftingmod.item.food.ItemFoodMuffinc;
import fr.mrlebest.craftingmod.item.food.ItemFoodMuffinf;
import fr.mrlebest.craftingmod.item.food.ItemFoodOignon;
import fr.mrlebest.craftingmod.item.food.ItemFoodPainf;
import fr.mrlebest.craftingmod.item.food.ItemFoodPoulet;
import fr.mrlebest.craftingmod.item.food.ItemFoodSalade;
import fr.mrlebest.craftingmod.item.food.ItemFoodTarte;
import fr.mrlebest.craftingmod.item.food.ItemFoodWhopper;
import fr.mrlebest.craftingmod.item.food.ItemFoodWrap;
import net.minecraft.item.Item;
import net.minecraft.item.ItemFood;

public class Items
{
    
    public static Item itemBaieOrange, itemPhone, itemMolette, itemPorteFeuille, itemTest, itemTphone, itemPain, itemBierre, itemBigKing, itemCoca, itemFrite, itemGateauChocolat, itemGauffre, itemKebab, itemMuffinChocolat, itemMuffinFraise, itemOignon, itemPainFrancais, itemPoulet, itemSalade, itemSprite, itemTarteGlace, itemVin, itemWhopper, itemWrap, itemBaton, itemCuivreF, itemFerF, itemRedBull,
    itemWater, itemMTN,itemBaieRouge, itemSacoche, itemSmallBackPack, itemBigBackPack, itemMillitaryBackPack, itemPoliceBackPack, itemBillet5, itemBillet10, itemBillet20, itemBillet50, itemBillet100, itemBillet200, itemBillet500, itemKey, itemAxe;
    
    public static void registerItems()
    {
        itemBillet5 = new Item().setUnlocalizedName("billet5").setTextureName("craftingmod:item_billet5").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet5, "item_billet5");
        itemBillet10 = new Item().setUnlocalizedName("billet10").setTextureName("craftingmod:item_billet10").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet10, "item_billet10");
        itemBillet20 = new Item().setUnlocalizedName("billet20").setTextureName("craftingmod:item_billet20").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet20, "item_billet20");
        itemBillet50 = new Item().setUnlocalizedName("billet50").setTextureName("craftingmod:item_billet50").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet50, "item_billet50");
        itemBillet100 = new Item().setUnlocalizedName("billet100").setTextureName("craftingmod:item_billet100").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet100, "item_billet100");
        itemBillet200 = new Item().setUnlocalizedName("billet200").setTextureName("craftingmod:item_billet200").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet200, "item_billet200");
        itemBillet500 = new Item().setUnlocalizedName("billet500").setTextureName("craftingmod:item_billet500").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBillet500, "item_billet500");
        itemKey = new Item().setUnlocalizedName("key").setTextureName("craftingmod:item_key").setMaxStackSize(1).setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemKey, "item_key");
        itemAxe = new Item().setUnlocalizedName("axe").setTextureName("craftingmod:item_axe").setMaxStackSize(1).setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemAxe, "item_axe");
        itemCuivreF = new ItemCuivreF().setUnlocalizedName("cuivref").setTextureName("craftingmod:item_cuivref").setMaxStackSize(8).setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemCuivreF, "item_cuivref");
        itemFerF = new ItemFerF().setUnlocalizedName("ferf").setTextureName("craftingmod:item_ferf").setMaxStackSize(8).setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemFerF, "item_ferf");
        itemBaieOrange = new ItemBaieOrange(2, 0.5F, true).setUnlocalizedName("baieorange").setTextureName("craftingmod:item_baieorange").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBaieOrange, "item_baieorange");
        itemBaieRouge = new ItemBaieRouge(2, 0.5F, true).setUnlocalizedName("baierouge").setTextureName("craftingmod:item_baierouge").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemBaieRouge, "item_baierouge");
        itemPhone = new ItemPhone().setUnlocalizedName("phone").setTextureName("craftingmod:item_phone").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemPhone, "item_phone");
        itemMolette = new ItemMolette().setUnlocalizedName("molette").setTextureName("craftingmod:item_molette").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemMolette, "item_molette");
        itemTest = new ItemTest().setUnlocalizedName("test").setTextureName("craftingmod:item_test").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemTest, "item_test");
        itemTphone = new ItemTphone().setUnlocalizedName("itemTphone").setTextureName("craftingmod:item_tphone").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemTphone, "item_tphone");
        itemRedBull = new ItemRedBull((short)10, 9.0F).setUnlocalizedName("redbull").setTextureName("craftingmod:item_redbull").setMaxStackSize(4);
        GameRegistry.registerItem(itemRedBull, "item_redbull");
        itemWater = new ItemWater((short)30, 0.0F).setUnlocalizedName("water").setTextureName("craftingmod:item_water").setMaxStackSize(4);
        GameRegistry.registerItem(itemWater, "item_water");
        itemMTN = new ItemMTN((short)15, 10.0F).setUnlocalizedName("mtn").setTextureName("craftingmod:item_mtn").setMaxStackSize(4);
        itemPorteFeuille = new ItemPorteFeuille().setUnlocalizedName("portefeuille").setTextureName("craftingmod:item_portefeuille").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemPorteFeuille, "item_portefeuille");
        itemSacoche = new ItemSacoche().setUnlocalizedName("sacoche").setTextureName("craftingmod:item_sacoche").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        GameRegistry.registerItem(itemSacoche, "item_sacoche");
        itemSmallBackPack = new ItemSmallBackPack().setUnlocalizedName("smallbackpack").setTextureName("craftingmod:item_smallbackpack").setCreativeTab(CraftingMod.craftingmodCreativeTabs).setMaxStackSize(1);
        GameRegistry.registerItem(itemSmallBackPack, "item_smallbackpack");
        itemBigBackPack = new ItemBigBackPack().setUnlocalizedName("bigbackpack").setTextureName("craftingmod:item_bigbackpack").setCreativeTab(CraftingMod.craftingmodCreativeTabs).setMaxStackSize(1);
        GameRegistry.registerItem(itemBigBackPack, "item_bigbackpack");
        itemMillitaryBackPack = new ItemMillitaryBackPack().setUnlocalizedName("millitarybackpack").setTextureName("craftingmod:item_millitarybackpack").setCreativeTab(CraftingMod.craftingmodCreativeTabs).setMaxStackSize(1);
        GameRegistry.registerItem(itemMillitaryBackPack, "item_millitarybackpack");
        itemPoliceBackPack = new ItemPoliceBackPack().setUnlocalizedName("policebackpack").setTextureName("craftingmod:item_policebackpack").setCreativeTab(CraftingMod.craftingmodCreativeTabs).setMaxStackSize(1);
        GameRegistry.registerItem(itemPoliceBackPack, "item_policebackpack");
        // itemBaton = new ItemBaton().setUnlocalizedName("itemBaton").setTextureName("craftingmod:item_baton").setCreativeTab(CraftingMod.craftingmodCreativeTabs);
        // GameRegistry.registerItem(itemBaton, "item_baton");
        itemBigKing = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemBigKing").setTextureName("craftingmod:itemBigKing").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemBierre = new ItemFoodBiere((short)20, 8.0F).setUnlocalizedName("itemBiere").setTextureName("craftingmod:itemBiere").setMaxStackSize(4);
        itemPoulet = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemPoulet").setTextureName("craftingmod:itemPoulet").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemVin = new ItemFoodVin((short)20, 8.0F).setUnlocalizedName("itemVin").setTextureName("craftingmod:itemVin").setMaxStackSize(4);
        itemCoca = new ItemFoodCoca((short)25, 7.2F).setUnlocalizedName("itemCoca").setTextureName("craftingmod:itemCoca").setMaxStackSize(4);
        itemFrite = new ItemFood(6, 0.5F, false).setUnlocalizedName("itemFrites").setTextureName("craftingmod:itemFrites").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemGateauChocolat = new ItemFood(4, 0.5F, false).setUnlocalizedName("itemGateauChocolat").setTextureName("craftingmod:itemGateauChocolat").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemGauffre = new ItemFood(4, 0.5F, false).setUnlocalizedName("itemGauffre").setTextureName("craftingmod:itemGauffre").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemKebab = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemKebab").setTextureName("craftingmod:itemKebab").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemMuffinFraise = new ItemFood(4, 0.5F, false).setUnlocalizedName("itemMuffinFraise").setTextureName("craftingmod:itemMuffinFraise").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemMuffinChocolat = new ItemFood(4, 0.5F, false).setUnlocalizedName("itemMuffinChocolat").setTextureName("craftingmod:itemMuffinChocolat").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemPain = new ItemFood(6, 0.5F, false).setUnlocalizedName("itemBaguette").setTextureName("craftingmod:itemBaguette").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemPainFrancais = new ItemFood(6, 0.5F, false).setUnlocalizedName("itemPainFrancais").setTextureName("craftingmod:itemPainFrancais").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemOignon = new ItemFood(6, 0.5F, false).setUnlocalizedName("itemOignon").setTextureName("craftingmod:itemOignon").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemSalade = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemSalade").setTextureName("craftingmod:itemSalade").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemSprite = new ItemFoodSprite((short)25, 7.2F).setUnlocalizedName("itemSprite").setTextureName("craftingmod:itemSprite").setMaxStackSize(4);
        itemTarteGlace = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemTarteGlace").setTextureName("craftingmod:itemTarteGlace").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemWhopper = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemWhopper").setTextureName("craftingmod:itemWhopper").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemWrap = new ItemFood(8, 0.5F, false).setUnlocalizedName("itemWrap").setTextureName("craftingmod:itemWrap").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemBigKing = new ItemFoodBigKing(8, 0.5F, false).setUnlocalizedName("itemBigKing").setTextureName("craftingmod:itemBigKing").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemPoulet = new ItemFoodPoulet(8, 0.5F, false).setUnlocalizedName("itemPoulet").setTextureName("craftingmod:itemPoulet").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemFrite = new ItemFoodFrites(6, 0.5F, false).setUnlocalizedName("itemFrites").setTextureName("craftingmod:itemFrites").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemGateauChocolat = new ItemFoodGateau(4, 0.5F, false).setUnlocalizedName("itemGateauChocolat").setTextureName("craftingmod:itemGateauChocolat").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemGauffre = new ItemFoodGauffre(4, 0.5F, false).setUnlocalizedName("itemGauffre").setTextureName("craftingmod:itemGauffre").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemKebab = new ItemFoodKebab(8, 0.5F, false).setUnlocalizedName("itemKebab").setTextureName("craftingmod:itemKebab").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemMuffinFraise = new ItemFoodMuffinf(4, 0.5F, false).setUnlocalizedName("itemMuffinFraise").setTextureName("craftingmod:itemMuffinFraise").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemMuffinChocolat = new ItemFoodMuffinc(4, 0.5F, false).setUnlocalizedName("itemMuffinChocolat").setTextureName("craftingmod:itemMuffinChocolat").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemPain = new ItemFoodBaguette(6, 0.5F, false).setUnlocalizedName("itemBaguette").setTextureName("craftingmod:itemBaguette").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemPainFrancais = new ItemFoodPainf(6, 0.5F, false).setUnlocalizedName("itemPainFrancais").setTextureName("craftingmod:itemPainFrancais").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemOignon = new ItemFoodOignon(6, 0.5F, false).setUnlocalizedName("itemOignon").setTextureName("craftingmod:itemOignon").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemSalade = new ItemFoodSalade(8, 0.5F, false).setUnlocalizedName("itemSalade").setTextureName("craftingmod:itemSalade").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemTarteGlace = new ItemFoodTarte(8, 0.5F, false).setUnlocalizedName("itemTarteGlace").setTextureName("craftingmod:itemTarteGlace").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemWhopper = new ItemFoodWhopper(8, 0.5F, false).setUnlocalizedName("itemWhopper").setTextureName("craftingmod:itemWhopper").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        itemWrap = new ItemFoodWrap(8, 0.5F, false).setUnlocalizedName("itemWrap").setTextureName("craftingmod:itemWrap").setCreativeTab(CraftingMod.craftingmodFoodCreativeTabs);
        GameRegistry.registerItem(itemBigKing, "itemBigKing");
        GameRegistry.registerItem(itemBierre, "itemBiere");
        GameRegistry.registerItem(itemPoulet, "itemPoulet");
        GameRegistry.registerItem(itemVin, "itemVin");
        GameRegistry.registerItem(itemCoca, "itemCoca");
        GameRegistry.registerItem(itemFrite, "itemFrites");
        GameRegistry.registerItem(itemGateauChocolat, "itemGateauChocolat");
        GameRegistry.registerItem(itemGauffre, "itemGauffre");
        GameRegistry.registerItem(itemKebab, "itemKebab");
        GameRegistry.registerItem(itemMuffinFraise, "itemMuffinFraise");
        GameRegistry.registerItem(itemMuffinChocolat, "itemMuffinChocolat");
        GameRegistry.registerItem(itemPain, "itemBaguette");
        GameRegistry.registerItem(itemPainFrancais, "itemPainFrancais");
        GameRegistry.registerItem(itemOignon, "itemOignon");
        GameRegistry.registerItem(itemSalade, "itemSalade");
        GameRegistry.registerItem(itemSprite, "itemSprite");
        GameRegistry.registerItem(itemTarteGlace, "itemTarteGlace");
        GameRegistry.registerItem(itemWhopper, "itemWhopper");
        GameRegistry.registerItem(itemWrap, "itemWrap");
    }

}
